[package]
name = "legacy-ios-restore"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
publish = false

[dependencies]
legacy-ios-core = { path = "../core" }
legacy-ios-firmware = { path = "../firmware" }
legacy-ios-image = { path = "../image" }
legacy-ios-services = { path = "../services" }
legacy-ios-transport = { path = "../transport" }
plist = "=1.8.0"
sha1 = "=0.10.6"
thiserror.workspace = true
tokio = { workspace = true, features = ["fs", "io-util"] }
tracing.workspace = true
uuid = { version = "1.16.0", features = ["v4"] }

[lints]
workspace = true
