[package]
name = "legacy-ios-kit-cli"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
publish = false

[[bin]]
name = "lik"
path = "src/main.rs"

[dependencies]
anyhow.workspace = true
clap = { version = "4.5.35", features = ["derive"] }
directories = "5.0.1"
hex = "=0.4.3"
legacy-ios-kit = { path = "../../crates/kit" }
rpassword = "=7.5.4"
serde.workspace = true
serde_json = "1.0.140"
tokio = { workspace = true, features = ["signal"] }
toml = "0.8.20"
tracing.workspace = true
tracing-subscriber = "0.3.19"

[lints]
workspace = true
