[package]
name = "legacy-ios-firmware"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
publish = false

[dependencies]
legacy-ios-assets = { path = "../assets" }
legacy-ios-core = { path = "../core" }
plist = "=1.8.0"
serde.workspace = true
thiserror.workspace = true

[lints]
workspace = true
