[package]
name = "legacy-ios-kit"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
publish = false

[dependencies]
legacy-ios-assets = { path = "../assets" }
legacy-ios-core = { path = "../core" }
legacy-ios-firmware = { path = "../firmware" }
legacy-ios-services = { path = "../services" }
legacy-ios-transport = { path = "../transport" }
legacy-ios-workflows = { path = "../workflows" }
plist = "=1.8.0"
serde.workspace = true
thiserror.workspace = true
tokio.workspace = true
tracing.workspace = true

[lints]
workspace = true
