[package]
name = "legacy-ios-image"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
publish = false

[dependencies]
aes = "=0.8.4"
bzip2-rs = "=0.1.2"
cbc = "=0.1.2"
crc32fast = "=1.5.1"
flate2 = { version = "=1.1.10", default-features = false, features = ["rust_backend"] }
legacy-ios-core = { path = "../core" }
plist = "=1.8.0"
thiserror.workspace = true

[dev-dependencies]
hex = "=0.4.3"

[lints]
workspace = true
